name: day_bus_user
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  cached_network_image: ^3.4.1
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.3
  go_router: ^17.0.1
  google_fonts: ^7.0.1
  pinput: ^6.0.1
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    
